// Writes src/content/books/index.generated.ts, which statically imports every book JSON file.
// Self-contained (node builtins only) so it also runs directly: `npm run content:index`.
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

// "book_" keeps every slug a valid identifier, including "1971-ship" or reserved words like "new".
const ident = (slug: string) => `book_${slug.replace(/-/g, "_")}`;

export function renderIndex(slugs: string[]): string {
  const sorted = [...slugs].sort();
  const imports = sorted.map((slug) => `import ${ident(slug)} from "./${slug}.json";`);
  const list = sorted.map((slug) => `${ident(slug)} as Book`).join(", ");
  return [
    "// Generated by src/studio/content-index.ts. Do not edit: run `npm run content:index` or use the studio.",
    'import type { Book } from "@/types/content";',
    ...imports,
    "",
    `export const realBooks: Book[] = [${list}];`,
    "",
  ].join("\n");
}

export function writeIndex(booksDir: string): void {
  const slugs = readdirSync(booksDir)
    .filter((name) => name.endsWith(".json"))
    .map((name) => name.replace(/\.json$/, ""));
  writeFileSync(path.join(booksDir, "index.generated.ts"), renderIndex(slugs));
}

// Run as a script (`node src/studio/content-index.ts`), not when imported.
if (process.argv[1] && import.meta.filename === path.resolve(process.argv[1])) {
  writeIndex(path.join(process.cwd(), "src", "content", "books"));
  console.log("Wrote src/content/books/index.generated.ts");
}
