// Generated by src/studio/content-index.ts. Do not edit: run `npm run content:index` or use the studio.
import type { Book } from "@/types/content";
import book_wakasamaru from "./wakasamaru.json";

export const realBooks: Book[] = [book_wakasamaru as Book];
