import type { Book, Chapter, PublicationStatus } from "@/types/content";

// TEST-ONLY catalog. It's loaded only when LEAF_E2E_FIXTURES=1 (the Playwright build; see
// src/content/books/index.ts). Its images are generated by scripts/make-e2e-fixtures.mjs into
// the gitignored public/novels/_e2e/. Never set the flag for a real build.

const WIDTH = 1000; // portrait 2:3, unlike Wakasamaru's landscape 3:2
const HEIGHT = 1500;
const BASE = "/novels/_e2e";
const pad = (n: number) => String(n).padStart(2, "0");

function chapter(
  bookSlug: string,
  slug: string,
  title: string,
  order: number,
  pageCount: number,
  status: PublicationStatus = "published",
): Chapter {
  return {
    id: `${bookSlug}-${slug}`,
    slug,
    title,
    order,
    status,
    pages: Array.from({ length: pageCount }, (_, i) => ({
      id: `${bookSlug}-${slug}-p${pad(i + 1)}`,
      order: i + 1,
      imageUrl: `${BASE}/${bookSlug}/${slug}/page-${pad(i + 1)}.webp`,
      width: WIDTH,
      height: HEIGHT,
    })),
  };
}

export const e2eFixtureBooks: Book[] = [
  {
    id: "e2e-atlas",
    slug: "e2e-atlas",
    title: "E2E Atlas",
    synopsis: "Test-only book with two released chapters, one draft chapter and portrait pages.",
    cover: { url: `${BASE}/e2e-atlas/cover.webp`, width: WIDTH, height: HEIGHT, alt: "E2E Atlas test cover" },
    genres: ["Fantasy"],
    status: "published",
    seriesStatus: "ongoing",
    chapters: [
      chapter("e2e-atlas", "chapter-01", "Chapter One", 1, 3),
      chapter("e2e-atlas", "chapter-02", "Chapter Two", 2, 2),
      chapter("e2e-atlas", "chapter-03", "Chapter Three", 3, 1, "draft"),
    ],
  },
  {
    id: "e2e-draft",
    slug: "e2e-draft",
    title: "E2E Draft",
    synopsis: "Test-only draft book that must never be visible.",
    cover: { url: `${BASE}/e2e-draft/cover.webp`, width: WIDTH, height: HEIGHT, alt: "E2E Draft test cover" },
    genres: ["Mystery"],
    status: "draft",
    chapters: [chapter("e2e-draft", "chapter-01", "Chapter One", 1, 1)],
  },
];
